[package]
name = "waitpidx"
version = "0.0.0"
authors = ["Konge <zkonge@outlook.com>"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/zkonge/waitpidx"
keywords = ["waitpid", "process", "linux"]
categories = ["os"]
readme = "README.md"

[dependencies]
rustix = { version = "1.1.4", default-features = false, features = [
    "std",
    "event",
    "process",
] }
tokio = { version = "1.49.0", default-features = false, features = [
    "net",
], optional = true }

[dev-dependencies]
tokio = { version = "1.49.0", features = ["rt"] }
futures-util = { version = "0.3.32", default-features = false, features = [
    "alloc",
] }

[features]
default = ["async"]
async = ["dep:tokio"]

[[example]]
name = "waitpid_async"
required-features = ["async"]

[[example]]
name = "waitpid_many_async"
required-features = ["async"]

[[example]]
name = "waitpid"
